from distutils.core import setup

setup(name='tulpenmanie',
      version='0.7.0',
      description='Graphical speculation platform',
      url='https://github.com/3M3RY/tulpenmanie',
      author='Emery Hemingway',
      author_email='tulpenmanie@emery.neomailbox.net',
      py_modules=['tulpenmanie.bitcoin',
                  'tulpenmanie.commodity',
                'tulpenmanie.exchange',
                'tulpenmanie.widget',
                'tulpenmanie.data.ticker',
                'tulpenmanie.data.orders',
                'tulpenmanie.data.funds',
                'tulpenmanie.exchange_modules.bitstamp',
                'tulpenmanie.exchange_modules.btc-e',
                'tulpenmanie.exchange_modules.campbx',
                'tulpenmanie.exchange_modules.mtgox_api1',
                'tulpenmanie.exchange_modules.virwox',
                'tulpenmanie.model.base',
                'tulpenmanie.model.order',
                'tulpenmanie.network.__init__',
                'tulpenmanie.ui.commodity',
                'tulpenmanie.ui.edit',
                'tulpenmanie.ui.exchange',
                'tulpenmanie.ui.mainwindow',
                'tulpenmanie.ui.market',
                'tulpenmanie.ui.transfer.bitcoin',
                ],

      scripts=['scripts/tulpenmanie'],
      requires=['PyQt4.QtCore',
                'PyQt4.GtGui',
                'PyQt4.QtNetwork'],
      provides=['tulpenmanie']
      )
