#!python

# This is only needed for Python v2 but is harmless for Python v3.
import sip
sip.setapi('QVariant', 2)

import pdb

import argparse
import logging
import os
import sys

from PyQt4 import QtCore, QtGui


try:
    import otapi
    otapi.OTAPI_Basic_AppStartup()
    otapi.OTAPI_Basic_Init()
    otapi.OTAPI_Basic_LoadWallet()
except ImportError:
    otapi = None

# Set the file creation mode to -rwx------
os.umask(63)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true',
                        help="print debugging messages to stderr "
                        "DEBUG LEVEL MAY PRINT PASSWORDS")
    parser.add_argument('-v', '--verbose', action='store_true',
                        help="print informative internal "
                        "messages to stderr")

    args = parser.parse_args()

    if args.verbose and not args.debug:
        log_level = logging.INFO
    elif args.debug:
        log_level = logging.DEBUG
        #otapi.OT_API_Output(5, "logging test");
    else:
        log_level = logging.WARNING
    logging.basicConfig(level=log_level)

    app = QtGui.QApplication(sys.argv)
    app.setOrganizationName("Emery")
    app.setApplicationName("dojima")
    app.setApplicationVersion('0.0.1')

    #start translation testing
    # translator = QtCore.QTranslator()
    # translator.load("farsi.qm")
    # app.installTranslator(translator)
    #end
    
    from dojima.ui.mainwindow import MainWindow
    window = MainWindow()
    window.show()

    exit_code = app.exec_()
    otapi.OTAPI_Basic_AppShutdown()
    
    sys.exit(exit_code)
