#!python

import argparse
import logging
import os
import sys
import tulpenmanie.manager

# Set the file creation mode to -rwx------
os.umask(63)

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--debug', action='store_true',
                    help="print debugging messages to stderr")
parser.add_argument('-v', '--verbose', action='store_true',
                    help="print informative internal "
                         "messages to stderr")
args = parser.parse_args()

if args.verbose and not args.debug:
    log_level = logging.INFO
elif args.debug:
    log_level = logging.DEBUG
else:
    log_level = logging.WARNING
logging.basicConfig(level=log_level)

manager = tulpenmanie.manager.Manager(sys.argv)
sys.exit(manager.run())
